name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  http: ^0.13.3
  permission_handler: ^11.3.0
  intl: ^0.17.0
  geolocator: ^11.0.0
  bot_toast: ^4.1.3
  flutter_background_service:
  flutter_background_service_android: 6.0.1
  beacon_scanner: ^0.0.4
  bluetooth_enable_fork: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
